stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - python -m ensurepip --upgrade
  - pip install --upgrade pip

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t gitlab-runner-config:latest .
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -d --name gitlab-runner-config -p 5000:5000 ai_app:latest
  only:
    - main
  tags:
    - docker,flask,islamai_runner