image: docker:latest

stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - apt-get update && apt-get install -y python3-pip
  - pip install --upgrade pip

build:
  stage: build
  script:
    - pip install -r requirements.txt
  tags:
    - docker
    - flask
  only:
    - main

deploy:
  stage: deploy
  script:
    - python3 -m compileall .
    - python3 ai_app.py
  tags:
    - docker
    - flask
  only:
    - main

