image: python:3.11-slim

stages:
  - setup
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - apt-get update && apt-get install -y python3-pip wget
  - wget -qO- https://get.docker.com | sh
  - sh get-docker.sh
  - service docker start
  - pip install --upgrade pip
  - pip install -r requirements.txt

setup:
  stage: setup
  tags:
    - docker
  script:
    - systemctl status docker.service
    - ls -l /var/run/docker.sock
    - docker info
  only:
    - main

build:
  stage: build
  tags:
    - docker
    - flask
  script:
    - docker build -t ai_app:latest .
  only:
    - main

deploy:
  stage: deploy
  tags:
    - docker
    - flask
  script:
    - docker run -d --name gitlab-runner-config -p 5000:5000 ai_app:latest
  only:
    - main
