image: python:3.11-slim

stages:
  - run

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - apt-get update && apt-get install -y python3-pip
  - pip install --upgrade pip
  - pip install -r requirements.txt

run:
  stage: run
  script:
    - python ai_app.py
  only:
    - main
