image: python:3.11-slim

stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - apt-get update && apt-get install -y python3-pip
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python -m unittest discover
  only:
    - main

deploy:
  stage: deploy
  script:
    - - docker run -d --name gitlab-runner-config -p 5000:5000 ai_app:latest
  only:
    - main
