stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"

cache:
  paths:
    - .pip_cache/

before_script:
  - python -m ensurepip --upgrade
  - pip install --upgrade pip

build:
  stage: build
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - python -m compileall .
  only:
    - main

deploy:
  stage: deploy
  image: python:3.10
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip install -r requirements.txt
    - pip install gunicorn
    - gunicorn -b 0.0.0.0:5000 app/ai_app:app
  only:
    - main
