stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - python3 -m ensurepip --upgrade
  - pip3 install --upgrade pip

build:
  stage: build
  tags:
    - docker
    - flask
  image: python:3.10-slim
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t ai_app:latest .
  only:
    - main

deploy:
  stage: deploy
  tags:
    - docker
    - flask
  image: docker:24.0.5
  services:
    - name: dind
  script:
    - docker run -d --name gitlab-runner-config -p 5000:5000 ai_app:latest
  only:
    - main
