stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  PORT: 5000

cache:
  paths:
    - .pip_cache/

before_script:
  - python3 -m ensurepip --upgrade
  - pip3 install --upgrade pip

build:
  stage: build
  image: python:3.10-slim
  services:
    - docker:dind
  script:
    - docker build -t ai_app:latest .
  only:
    - main

deploy:
  stage: deploy
  image: python:3.10-slim
  services:
    - docker:dind
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip install -r requirements.txt
    - pip install gunicorn
    - docker run -d --name gitlab-runner-config -p 5000:5000 ai_app:latest
  only:
    - main
  tags:
    - docker,flask,islamai_runner